apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 80
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: backend
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: backend
          image: mariacontins/scc57503-backend
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_URL
              value: "redis"
            - name: REDIS_KEY
              value: ""
            - name: REDIS_SSL
              value: "0"
            - name: CACHE_ON
              value: "1"
            - name: mongoConnectionString
              value: "mongodb://root:root@mongo:27017/"
            - name: SEARCH_ENABLED
              value: "0"
            - name: SEARCH_QUERY_KEY
              value: ""
            - name: SEARCH_URL
              value: ""
            - name: SEARCH_INDEX
              value: ""
            - name: SEARCH_QUERY_KEY
              value: ""
            - name: MEDIA_STORAGE
              value: "FILESYSTEM" #Possible values "FILESYSTEM" or "BLOBSTORE"
            - name: storagePath
              value: "/mnt/files/"
          volumeMounts:
            - mountPath: "/mnt/files"
              name: blob-storage-volume
      volumes:
        - name: blob-storage-volume
          persistentVolumeClaim:
            claimName: azure-managed-disk
---

