apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
    - port: 27017
  selector:
    app: mongo

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: mongo
          image: mongo
          env:
            - name: "MONGO_INITDB_ROOT_USERNAME"
              value: root
            - name: "MONGO_INITDB_ROOT_PASSWORD"
              value: root
          ports:
            - containerPort: 27017
              name: mongo
          volumeMounts:
            - mountPath: "/data/db"
              name: mongo-volume
      volumes:
        - name: mongo-volume
          persistentVolumeClaim:
            claimName: mongo-pvc
---
