apiVersion: v1
kind: Service
metadata:
  name: mongo-express
spec:
  type: LoadBalancer
  selector:
    app: mongo-express
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: mongo-express
          image: mongo-express
          env:
            - name: "ME_CONFIG_MONGODB_ADMINUSERNAME"
              value: root
            - name: "ME_CONFIG_MONGODB_ADMINPASSWORD"
              value: root
            - name: "ME_CONFIG_MONGODB_URL"
              value: "mongodb://root:root@mongo:27017/"
            - name: "ME_CONFIG_BASICAUTH_USERNAME"
              value: "mongo"
            - name: "ME_CONFIG_BASICAUTH_PASSWORD"
              value: "mongo"
          ports:
            - containerPort: 8081
              name: mongo
---

